set(SOURCES_CLIENT
	${CMAKE_SOURCE_DIR}/game/shared/hl2/basehlcombatweapon_shared.cpp
	${CMAKE_SOURCE_DIR}/game/shared/hl2/achievements_hl2.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_antlion_dust.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_ar2_explosion.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_barnacle.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_barney.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_basehelicopter.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_basehlcombatweapon.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_basehlplayer.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_citadel_effects.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_corpse.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_env_alyxtemp.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_env_headcrabcanister.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_env_starfield.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_func_tankmortar.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_hl2_playerlocaldata.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_info_teleporter_countdown.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_npc_antlionguard.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_npc_combinegunship.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_npc_manhack.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_npc_rollermine.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_plasma_beam_node.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_prop_combine_ball.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_rotorwash.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_script_intro.cpp
	${CMAKE_SOURCE_DIR}/game/shared/script_intro_shared.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_strider.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_te_concussiveexplosion.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_te_flare.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_thumper_dust.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_vehicle_airboat.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_vehicle_cannon.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_vehicle_crane.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_vehicle_prisoner_pod.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_weapon__stubs_hl2.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_weapon_crossbow.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_weapon_physcannon.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/c_weapon_stunstick.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/clientmode_hlnormal.cpp
	${CMAKE_SOURCE_DIR}/game/client/death.cpp
	${CMAKE_SOURCE_DIR}/game/shared/hl2/env_headcrabcanister_shared.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/fx_antlion.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/fx_bugbait.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/fx_hl2_impacts.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/fx_hl2_tracers.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hl2_clientmode.cpp
	${CMAKE_SOURCE_DIR}/game/shared/hl2/hl2_gamerules.cpp
	${CMAKE_SOURCE_DIR}/game/shared/hl2/hl2_usermessages.cpp
	${CMAKE_SOURCE_DIR}/game/shared/hl2/hl_gamemovement.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hl_in_main.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hl_prediction.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_ammo.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_battery.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_blood.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_credits.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_damageindicator.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_flashlight.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_health.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_poisondamageindicator.cpp
	${CMAKE_SOURCE_DIR}/game/client/hud_posture.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_quickinfo.cpp
	${CMAKE_SOURCE_DIR}/game/client/hud_squadstatus.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_suitpower.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_weaponselection.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/hud_zoom.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/shieldproxy.cpp
	${CMAKE_SOURCE_DIR}/game/client/hl2/vgui_rootpanel_hl2.cpp
	${CMAKE_SOURCE_DIR}/game/client/episodic/c_vort_charge_token.cpp
)
