set(SOURCES_GLVIEW
	${CMAKE_SOURCE_DIR}/utils/glview/glview.cpp
	${CMAKE_SOURCE_DIR}/utils/glview/glos.h
	${CMAKE_SOURCE_DIR}/utils/common/cmdlib.cpp
	${CMAKE_SOURCE_DIR}/utils/common/filesystem_tools.cpp
	${CMAKE_SOURCE_DIR}/utils/common/physdll.cpp
	${CMAKE_SOURCE_DIR}/utils/common/cmdlib.h
	${CMAKE_SOURCE_DIR}/public/mathlib/mathlib.h
)
