set(SOURCES_MATHLIB
mathlib/3dnow.cpp
mathlib/almostequal.cpp
mathlib/anorms.cpp
mathlib/bumpvects.cpp
mathlib/color_conversion.cpp
mathlib/halton.cpp
mathlib/IceKey.cpp
mathlib/imagequant.cpp
mathlib/lightdesc.cpp
mathlib/mathlib_base.cpp
mathlib/polyhedron.cpp
mathlib/powsse.cpp
mathlib/quantize.cpp
mathlib/randsse.cpp
mathlib/simdvectormatrix.cpp
mathlib/sparse_convolution_noise.cpp
mathlib/spherical.cpp
mathlib/sseconst.cpp
mathlib/sse.cpp
mathlib/ssenoise.cpp
mathlib/vector.cpp
mathlib/vmatrix.cpp
)

set(HEADERS_MATHLIB
mathlib/3dnow.h
mathlib/noisedata.h
mathlib/sse.h
)
