set(SOURCES_GAME_SHARED
game/shared/achievementmgr.cpp
game/shared/achievement_saverestore.cpp
game/shared/achievements_hlx.cpp
game/shared/activitylist.cpp
game/shared/ammodef.cpp
game/shared/animation.cpp
game/shared/baseachievement.cpp
game/shared/basecombatcharacter_shared.cpp
game/shared/basecombatweapon_shared.cpp
game/shared/baseentity_shared.cpp
game/shared/basegrenade_shared.cpp
game/shared/baseparticleentity.cpp
game/shared/base_playeranimstate.cpp
game/shared/baseplayer_shared.cpp
game/shared/baseprojectile.cpp
game/shared/baseviewmodel_shared.cpp
game/shared/beam_shared.cpp
game/shared/cam_thirdperson.cpp
game/shared/choreoactor.cpp
game/shared/choreochannel.cpp
game/shared/choreoevent.cpp
game/shared/choreoscene.cpp
game/shared/collisionproperty.cpp
game/shared/cs_achievements_and_stats_interface.cpp
game/shared/death_pose.cpp
game/shared/debugoverlay_null.cpp
game/shared/debugoverlay_shared.cpp
game/shared/decals.cpp
game/shared/effect_dispatch_data.cpp
game/shared/ehandle.cpp
game/shared/entitylist_base.cpp
game/shared/EntityParticleTrail_Shared.cpp
game/shared/env_detail_controller.cpp
game/shared/env_meteor_shared.cpp
game/shared/env_wind_shared.cpp
game/shared/episodic/achievements_ep1.cpp
game/shared/episodic/achievements_ep2.cpp
game/shared/episodic/achievements_epx.cpp
game/shared/eventlist.cpp
game/shared/func_ladder.cpp
game/shared/gamemovement.cpp
game/shared/gamerules.cpp
game/shared/gamerules_register.cpp
game/shared/GameStats.cpp
game/shared/gamestringpool.cpp
game/shared/gamevars_shared.cpp
game/shared/hintmessage.cpp
game/shared/hintsystem.cpp
game/shared/hl2/achievements_hl2.cpp
game/shared/hl2/basehlcombatweapon_shared.cpp
game/shared/hl2/env_headcrabcanister_shared.cpp
game/shared/hl2/hl2_gamerules.cpp
game/shared/hl2/hl2_usermessages.cpp
game/shared/hl2/hl_gamemovement.cpp
game/shared/hl2mp/hl2mp_gamerules.cpp
game/shared/hl2mp/hl2mp_player_shared.cpp
game/shared/hl2mp/hl2mp_weapon_parse.cpp
game/shared/hl2mp/weapon_357.cpp
game/shared/hl2mp/weapon_ar2.cpp
game/shared/hl2mp/weapon_crossbow.cpp
game/shared/hl2mp/weapon_crowbar.cpp
game/shared/hl2mp/weapon_frag.cpp
game/shared/hl2mp/weapon_hl2mpbasebasebludgeon.cpp
game/shared/hl2mp/weapon_hl2mpbase.cpp
game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.cpp
game/shared/hl2mp/weapon_hl2mpbase_machinegun.cpp
game/shared/hl2mp/weapon_physcannon.cpp
game/shared/hl2mp/weapon_pistol.cpp
game/shared/hl2mp/weapon_rpg.cpp
game/shared/hl2mp/weapon_shotgun.cpp
game/shared/hl2mp/weapon_slam.cpp
game/shared/hl2mp/weapon_smg1.cpp
game/shared/hl2mp/weapon_stunstick.cpp
game/shared/hl2/survival_gamerules.cpp
game/shared/igamesystem.cpp
game/shared/interval.cpp
game/shared/mapentities_shared.cpp
game/shared/ModelSoundsCache.cpp
game/shared/movevars_shared.cpp
game/shared/mp_shareddefs.cpp
game/shared/Multiplayer/multiplayer_animstate.cpp
game/shared/multiplay_gamerules.cpp
game/shared/obstacle_pushaway.cpp
game/shared/particle_parse.cpp
game/shared/particle_property.cpp
game/shared/particlesystemquery.cpp
game/shared/physics_main_shared.cpp
game/shared/physics_saverestore.cpp
game/shared/physics_shared.cpp
game/shared/playerclass_info_parse.cpp
game/shared/point_bonusmaps_accessor.cpp
game/shared/point_posecontroller.cpp
game/shared/precache_register.cpp
game/shared/predictableid.cpp
game/shared/predicted_viewmodel.cpp
game/shared/predictioncopy.cpp
game/shared/props_shared.cpp
game/shared/querycache.cpp
game/shared/ragdoll_shared.cpp
game/shared/rope_helpers.cpp
game/shared/saverestore.cpp
game/shared/SceneCache.cpp
game/shared/sceneentity_shared.cpp
game/shared/sceneimage.cpp
game/shared/script_intro_shared.cpp
game/shared/sdk/sdk_basegrenade_projectile.cpp
game/shared/sdk/sdk_fx_shared.cpp
game/shared/sdk/sdk_gamemovement.cpp
game/shared/sdk/sdk_gamerules.cpp
game/shared/sdk/sdk_playeranimstate.cpp
game/shared/sdk/sdk_playerclass_info_parse.cpp
game/shared/sdk/sdk_player_shared.cpp
game/shared/sdk/sdk_shareddefs.cpp
game/shared/sdk/sdk_usermessages.cpp
game/shared/sdk/sdk_weapon_melee.cpp
game/shared/sdk/sdk_weapon_parse.cpp
game/shared/sdk/weapon_basesdkgrenade.cpp
game/shared/sdk/weapon_crowbar.cpp
game/shared/sdk/weapon_grenade.cpp
game/shared/sdk/weapon_mp5.cpp
game/shared/sdk/weapon_pistol.cpp
game/shared/sdk/weapon_sdkbase.cpp
game/shared/sdk/weapon_shotgun.cpp
game/shared/sequence_Transitioner.cpp
game/shared/SharedFunctorUtils.cpp
game/shared/sheetsimulator.cpp
game/shared/simtimer.cpp
game/shared/singleplay_gamerules.cpp
game/shared/sixense/sixense_convars.cpp
game/shared/SoundEmitterSystem.cpp
game/shared/soundenvelope.cpp
game/shared/Sprite.cpp
game/shared/SpriteTrail.cpp
game/shared/studio_shared.cpp
game/shared/takedamageinfo.cpp
game/shared/teamplay_gamerules.cpp
game/shared/teamplayroundbased_gamerules.cpp
game/shared/teamplay_round_timer.cpp
game/shared/test_ehandle.cpp
game/shared/usercmd.cpp
game/shared/usermessages.cpp
game/shared/util_shared.cpp
game/shared/vehicle_viewblend_shared.cpp
game/shared/voice_banmgr.cpp
game/shared/voice_gamemgr.cpp
game/shared/voice_status.cpp
game/shared/weapon_ifmbasecamera.cpp
game/shared/weapon_ifmbase.cpp
game/shared/weapon_ifmsteadycam.cpp
game/shared/weapon_parse.cpp
game/shared/weapon_parse_default.cpp
game/shared/weapon_proficiency.cpp
)

set(HEADERS_GAME_SHARED
game/shared/achievementmgr.h
game/shared/achievements_and_stats_interface.h
game/shared/achievement_saverestore.h
game/shared/activitylist.h
game/shared/ai_activity.h
game/shared/ai_debug_shared.h
game/shared/ammodef.h
game/shared/animation.h
game/shared/apparent_velocity_helper.h
game/shared/baseachievement.h
game/shared/basecombatweapon_shared.h
game/shared/baseentity_shared.h
game/shared/basegrenade_shared.h
game/shared/baseparticleentity.h
game/shared/base_playeranimstate.h
game/shared/baseplayer_shared.h
game/shared/baseprojectile.h
game/shared/baseviewmodel_shared.h
game/shared/beam_flags.h
game/shared/beam_shared.h
game/shared/cam_thirdperson.h
game/shared/choreoactor.h
game/shared/choreochannel.h
game/shared/choreoevent.h
game/shared/choreoscene.h
game/shared/collisionproperty.h
game/shared/cs_achievements_and_stats_interface.h
game/shared/death_pose.h
game/shared/debugoverlay_shared.h
game/shared/decals.h
game/shared/econ/ihasowner.h
game/shared/effect_color_tables.h
game/shared/effect_dispatch_data.h
game/shared/ehandle.h
game/shared/entitydatainstantiator.h
game/shared/entitylist_base.h
game/shared/entityparticletrail_shared.h
game/shared/env_detail_controller.h
game/shared/env_meteor_shared.h
game/shared/env_wind_shared.h
game/shared/episodic/npc_advisor_shared.h
game/shared/eventlist.h
game/shared/expressionsample.h
game/shared/forcefeedback.h
game/shared/func_dust_shared.h
game/shared/func_ladder.h
game/shared/gameeventdefs.h
game/shared/GameEventListener.h
game/shared/gamemovement.h
game/shared/gamerules.h
game/shared/gamerules_register.h
game/shared/gamestats.h
game/shared/gamestringpool.h
game/shared/gamevars_shared.h
game/shared/groundlink.h
game/shared/hintmessage.h
game/shared/hintsystem.h
game/shared/hl2/basehlcombatweapon_shared.h
game/shared/hl2/citadel_effects_shared.h
game/shared/hl2/env_alyxemp_shared.h
game/shared/hl2/env_headcrabcanister_shared.h
game/shared/hl2/hl2_gamerules.h
game/shared/hl2/hl2_player_shared.h
game/shared/hl2/hl2_shareddefs.h
game/shared/hl2/hl2_vehicle_radar.h
game/shared/hl2/hl_gamemovement.h
game/shared/hl2/hl_movedata.h
game/shared/hl2mp/hl2mp_gamerules.h
game/shared/hl2mp/hl2mp_player_shared.h
game/shared/hl2mp/hl2mp_weapon_parse.h
game/shared/hl2mp/weapon_ar2.h
game/shared/hl2mp/weapon_crowbar.h
game/shared/hl2mp/weapon_hl2mpbasebasebludgeon.h
game/shared/hl2mp/weapon_hl2mpbase.h
game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.h
game/shared/hl2mp/weapon_hl2mpbase_machinegun.h
game/shared/hl2mp/weapon_physcannon.h
game/shared/hl2mp/weapon_rpg.h
game/shared/hl2mp/weapon_slam.h
game/shared/ichoreoeventcallback.h
game/shared/IEffects.h
game/shared/igamemovement.h
game/shared/igamesystem.h
game/shared/imovehelper.h
game/shared/in_buttons.h
game/shared/interval.h
game/shared/iplayeranimstate.h
game/shared/ipredictionsystem.h
game/shared/iscenetokenprocessor.h
game/shared/itempents.h
game/shared/IVehicle.h
game/shared/mapdata_shared.h
game/shared/mapentities_shared.h
game/shared/ModelSoundsCache.h
game/shared/movetype_push.h
game/shared/movevars_shared.h
game/shared/mp_shareddefs.h
game/shared/Multiplayer/multiplayer_animstate.h
game/shared/multiplay_gamerules.h
game/shared/npcevent.h
game/shared/obstacle_pushaway.h
game/shared/particle_parse.h
game/shared/particle_property.h
game/shared/particle_property_inlines.h
game/shared/physics_saverestore.h
game/shared/physics_shared.h
game/shared/playerclass_info_parse.h
game/shared/playernet_vars.h
game/shared/point_bonusmaps_accessor.h
game/shared/point_posecontroller.h
game/shared/positionwatcher.h
game/shared/precache_register.h
game/shared/precipitation_shared.h
game/shared/predictable_entity.h
game/shared/predictableid.h
game/shared/predicted_viewmodel.h
game/shared/predictioncopy.h
game/shared/props_shared.h
game/shared/querycache.h
game/shared/ragdoll_shared.h
game/shared/rope_helpers.h
game/shared/rumble_shared.h
game/shared/saverestore_bitstring.h
game/shared/saverestore.h
game/shared/saverestore_stringtable.h
game/shared/saverestore_utlclass.h
game/shared/saverestore_utlmap.h
game/shared/saverestore_utlrbtree.h
game/shared/saverestore_utlsymbol.h
game/shared/saverestore_utlvector.h
game/shared/SceneCache.h
game/shared/sceneentity_shared.h
game/shared/sceneimage.h
game/shared/scriptevent.h
game/shared/sdk/sdk_basegrenade_projectile.h
game/shared/sdk/sdk_fx_shared.h
game/shared/sdk/sdk_gamerules.h
game/shared/sdk/sdk_playeranimstate.h
game/shared/sdk/sdk_playerclass_info_parse.h
game/shared/sdk/sdk_player_shared.h
game/shared/sdk/sdk_shareddefs.h
game/shared/sdk/sdk_weapon_melee.h
game/shared/sdk/sdk_weapon_parse.h
game/shared/sdk/weapon_basesdkgrenade.h
game/shared/sdk/weapon_grenade.h
game/shared/sdk/weapon_sdkbase.h
game/shared/sequence_Transitioner.h
game/shared/shared_classnames.h
game/shared/shareddefs.h
game/shared/SharedFunctorUtils.h
game/shared/sharedInterface.h
game/shared/sheetsimulator.h
game/shared/shot_manipulator.h
game/shared/simtimer.h
game/shared/singleplay_gamerules.h
game/shared/sixense/sixense_convars_extern.h
game/shared/smoke_fog_overlay_shared.h
game/shared/solidsetdefaults.h
game/shared/soundenvelope.h
game/shared/Sprite.h
game/shared/SpriteTrail.h
game/shared/sun_shared.h
game/shared/takedamageinfo.h
game/shared/teamplay_gamerules.h
game/shared/teamplayroundbased_gamerules.h
game/shared/teamplay_round_timer.h
game/shared/tempentity.h
game/shared/touchlink.h
game/shared/usercmd.h
game/shared/usermessages.h
game/shared/util_shared.h
game/shared/vehicle_choreo_generic_shared.h
game/shared/vehicle_viewblend_shared.h
game/shared/vgui_defaultinputsignal.h
game/shared/viewport_panel_names.h
game/shared/voice_banmgr.h
game/shared/voice_common.h
game/shared/voice_gamemgr.h
game/shared/voice_status.h
game/shared/vphysics_sound.h
game/shared/vphysicsupdateai.h
game/shared/weapon_ifmbasecamera.h
game/shared/weapon_ifmbase.h
game/shared/weapon_ifmsteadycam.h
game/shared/weapon_parse.h
game/shared/weapon_proficiency.h
)
