set(SOURCES_VBSP
	${CMAKE_SOURCE_DIR}/utils/vbsp/boundbox.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/brushbsp.cpp
	${CMAKE_SOURCE_DIR}/public/CollisionUtils.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/csg.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/cubemap.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/detail.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/detailObjects.cpp
	${CMAKE_SOURCE_DIR}/public/disp_common.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/disp_ivp.cpp
	${CMAKE_SOURCE_DIR}/public/disp_powerinfo.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/disp_vbsp.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/faces.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/glfile.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/ivp.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/leakfile.cpp
	${CMAKE_SOURCE_DIR}/public/loadcmdline.cpp
	${CMAKE_SOURCE_DIR}/public/lumpfiles.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/map.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/manifest.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/materialpatch.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/materialsub.cpp
	${CMAKE_SOURCE_DIR}/utils/common/mstristrip.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/nodraw.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/normals.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/overlay.cpp
	${CMAKE_SOURCE_DIR}/utils/common/physdll.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/portals.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/prtfile.cpp
	${CMAKE_SOURCE_DIR}/public/ScratchPad3D.cpp
	${CMAKE_SOURCE_DIR}/utils/common/scratchpad_helpers.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/StaticProp.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/textures.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/tree.cpp
	${CMAKE_SOURCE_DIR}/utils/common/utilmatlib.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/vbsp.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/worldvertextransitionfixup.cpp
	${CMAKE_SOURCE_DIR}/utils/vbsp/writebsp.cpp
	${CMAKE_SOURCE_DIR}/public/zip_utils.cpp
	${CMAKE_SOURCE_DIR}/utils/common/bsplib.cpp
	${CMAKE_SOURCE_DIR}/public/builddisp.cpp
	${CMAKE_SOURCE_DIR}/public/ChunkFile.cpp
	${CMAKE_SOURCE_DIR}/utils/common/cmdlib.cpp
	${CMAKE_SOURCE_DIR}/public/filesystem_helpers.cpp
	${CMAKE_SOURCE_DIR}/public/filesystem_init.cpp
	${CMAKE_SOURCE_DIR}/utils/common/filesystem_tools.cpp
	${CMAKE_SOURCE_DIR}/utils/common/map_shared.cpp
	${CMAKE_SOURCE_DIR}/utils/common/pacifier.cpp
	${CMAKE_SOURCE_DIR}/utils/common/polylib.cpp
	${CMAKE_SOURCE_DIR}/utils/common/scriplib.cpp
	${CMAKE_SOURCE_DIR}/utils/common/threads.cpp
)
