set(SOURCES_GAME_CLIENT
game/client/achievement_notification_panel.cpp
game/client/alphamaterialproxy.cpp
game/client/animatedentitytextureproxy.cpp
game/client/animatedoffsettextureproxy.cpp
game/client/animatedtextureproxy.cpp
game/client/AnimateSpecificTextureProxy.cpp
game/client/baseanimatedtextureproxy.cpp
game/client/baseclientrendertargets.cpp
game/client/basepresence.cpp
game/client/basepresence_xbox.cpp
game/client/beamdraw.cpp
game/client/bone_merge_cache.cpp
game/client/c_ai_basehumanoid.cpp
game/client/c_ai_basenpc.cpp
game/client/camomaterialproxy.cpp
game/client/c_baseanimating.cpp
game/client/c_baseanimatingoverlay.cpp
game/client/c_basecombatcharacter.cpp
game/client/c_basecombatweapon.cpp
game/client/c_basedoor.cpp
game/client/c_baseentity.cpp
game/client/c_baseflex.cpp
game/client/c_baseplayer.cpp
game/client/c_basetempentity.cpp
game/client/c_baseviewmodel.cpp
game/client/c_breakableprop.cpp
game/client/c_colorcorrection.cpp
game/client/c_colorcorrectionvolume.cpp
game/client/cdll_bounded_cvars.cpp
game/client/cdll_client_int.cpp
game/client/cdll_util.cpp
game/client/c_dynamiclight.cpp
game/client/c_effects.cpp
game/client/c_entitydissolve.cpp
game/client/c_entityparticletrail.cpp
game/client/c_env_fog_controller.cpp
game/client/c_env_particlescript.cpp
game/client/c_env_projectedtexture.cpp
game/client/c_env_screenoverlay.cpp
game/client/c_env_tonemap_controller.cpp
game/client/c_fire_smoke.cpp
game/client/c_fish.cpp
game/client/c_forcefeedback.cpp
game/client/c_func_areaportalwindow.cpp
game/client/c_func_breakablesurf.cpp
game/client/c_func_conveyor.cpp
game/client/c_func_dust.cpp
game/client/c_func_lod.cpp
game/client/c_func_occluder.cpp
game/client/c_func_reflective_glass.cpp
game/client/c_func_rotating.cpp
game/client/c_func_smokevolume.cpp
game/client/c_func_tracktrain.cpp
game/client/c_gib.cpp
game/client/c_hairball.cpp
game/client/c_impact_effects.cpp
game/client/c_info_overlay_accessor.cpp
game/client/classmap.cpp
game/client/clienteffectprecachesystem.cpp
game/client/cliententitylist.cpp
game/client/client_factorylist.cpp
game/client/clientleafsystem.cpp
game/client/clientmode_normal.cpp
game/client/clientmode_shared.cpp
game/client/clientshadowmgr.cpp
game/client/clientsideeffects.cpp
game/client/clientsideeffects_test.cpp
game/client/clientsteamcontext.cpp
game/client/client_thinklist.cpp
game/client/client_virtualreality.cpp
game/client/c_lightglow.cpp
game/client/cl_mat_stub.cpp
game/client/C_MaterialModifyControl.cpp
game/client/c_movie_explosion.cpp
game/client/colorcorrectionmgr.cpp
game/client/commentary_modelviewer.cpp
game/client/c_particle_fire.cpp
game/client/c_particle_smokegrenade.cpp
game/client/c_particle_system.cpp
game/client/c_physbox.cpp
game/client/c_physicsprop.cpp
game/client/c_physmagnet.cpp
game/client/c_pixel_visibility.cpp
game/client/c_plasma.cpp
game/client/c_playerresource.cpp
game/client/c_point_camera.cpp
game/client/c_point_commentary_node.cpp
game/client/c_props.cpp
game/client/c_prop_vehicle.cpp
game/client/c_ragdoll_manager.cpp
game/client/c_recipientfilter.cpp
game/client/c_rope.cpp
game/client/c_rumble.cpp
game/client/c_sceneentity.cpp
game/client/c_shadowcontrol.cpp
game/client/c_slideshow_display.cpp
game/client/c_smokestack.cpp
game/client/c_smoke_trail.cpp
game/client/c_soundscape.cpp
game/client/c_spotlight_end.cpp
game/client/c_sprite.cpp
game/client/c_sprite_perfmonitor.cpp
game/client/c_steamjet.cpp
game/client/c_stickybolt.cpp
game/client/c_sun.cpp
game/client/c_team.cpp
game/client/c_team_objectiveresource.cpp
game/client/c_team_train_watcher.cpp
game/client/c_te_armorricochet.cpp
game/client/c_te_basebeam.cpp
game/client/c_te_beamentpoint.cpp
game/client/c_te_beaments.cpp
game/client/c_te_beamfollow.cpp
game/client/c_te_beamlaser.cpp
game/client/c_te_beampoints.cpp
game/client/c_te_beamring.cpp
game/client/c_te_beamringpoint.cpp
game/client/c_te_beamspline.cpp
game/client/c_te_bloodsprite.cpp
game/client/c_te_bloodstream.cpp
game/client/c_te_breakmodel.cpp
game/client/c_te_bspdecal.cpp
game/client/c_te_bubbles.cpp
game/client/c_te_bubbletrail.cpp
game/client/c_te_clientprojectile.cpp
game/client/c_te.cpp
game/client/c_te_decal.cpp
game/client/c_te_dynamiclight.cpp
game/client/c_te_effect_dispatch.cpp
game/client/c_te_energysplash.cpp
game/client/c_te_explosion.cpp
game/client/c_te_fizz.cpp
game/client/c_te_footprint.cpp
game/client/c_te_glassshatter.cpp
game/client/c_te_glowsprite.cpp
game/client/c_te_impact.cpp
game/client/c_te_killplayerattachments.cpp
game/client/c_te_largefunnel.cpp
game/client/c_te_legacytempents.cpp
game/client/c_te_muzzleflash.cpp
game/client/c_te_particlesystem.cpp
game/client/c_te_physicsprop.cpp
game/client/c_te_playerdecal.cpp
game/client/c_te_projecteddecal.cpp
game/client/c_te_showline.cpp
game/client/c_tesla.cpp
game/client/c_te_smoke.cpp
game/client/c_te_sparks.cpp
game/client/c_te_sprite.cpp
game/client/c_te_spritespray.cpp
game/client/c_test_proxytoggle.cpp
game/client/c_testtraceline.cpp
game/client/c_te_worlddecal.cpp
game/client/c_tracer.cpp
game/client/c_user_message_register.cpp
game/client/c_vehicle_choreo_generic.cpp
game/client/c_vehicle_jeep.cpp
game/client/c_vguiscreen.cpp
game/client/c_vote_controller.cpp
game/client/C_WaterLODControl.cpp
game/client/c_world.cpp
game/client/death.cpp
game/client/detailobjectsystem.cpp
game/client/dummyproxy.cpp
game/client/EffectsClient.cpp
game/client/entity_client_tools.cpp
game/client/entityoriginmaterialproxy.cpp
game/client/episodic/c_npc_advisor.cpp
game/client/episodic/c_npc_puppet.cpp
game/client/episodic/c_prop_coreball.cpp
game/client/episodic/c_prop_scalable.cpp
game/client/episodic/c_vehicle_jeep_episodic.cpp
game/client/episodic/c_vort_charge_token.cpp
game/client/episodic/c_weapon_hopwire.cpp
game/client/episodic/episodic_screenspaceeffects.cpp
game/client/episodic/flesh_internal_material_proxy.cpp
game/client/flashlighteffect.cpp
game/client/functionproxy.cpp
game/client/fx_blood.cpp
game/client/fx.cpp
game/client/fx_cube.cpp
game/client/fx_discreetline.cpp
game/client/fx_envelope.cpp
game/client/fx_explosion.cpp
game/client/fx_fleck.cpp
game/client/fx_impact.cpp
game/client/fx_interpvalue.cpp
game/client/fx_line.cpp
game/client/fx_quad.cpp
game/client/fx_shelleject.cpp
game/client/fx_sparks.cpp
game/client/fx_staticline.cpp
game/client/fx_tracer.cpp
game/client/fx_trail.cpp
game/client/fx_water.cpp
game/client/game_controls/basemodel_panel.cpp
game/client/game_controls/basemodelpanel.cpp
game/client/game_controls/baseviewport.cpp
game/client/game_controls/buymenu.cpp
game/client/game_controls/buysubmenu.cpp
game/client/game_controls/classmenu.cpp
game/client/game_controls/ClientScoreBoardDialog.cpp
game/client/game_controls/commandmenu.cpp
game/client/game_controls/IconPanel.cpp
game/client/game_controls/intromenu.cpp
game/client/game_controls/MapOverview.cpp
game/client/game_controls/NavProgress.cpp
game/client/game_controls/SpectatorGUI.cpp
game/client/game_controls/teammenu.cpp
game/client/game_controls/vguitextwindow.cpp
game/client/gametrace_client.cpp
game/client/geiger.cpp
game/client/glow_outline_effect.cpp
game/client/glow_overlay.cpp
game/client/history_resource.cpp
game/client/hl2/c_antlion_dust.cpp
game/client/hl2/c_ar2_explosion.cpp
game/client/hl2/c_barnacle.cpp
game/client/hl2/c_barney.cpp
game/client/hl2/c_basehelicopter.cpp
game/client/hl2/c_basehlcombatweapon.cpp
game/client/hl2/c_basehlplayer.cpp
game/client/hl2/c_citadel_effects.cpp
game/client/hl2/c_corpse.cpp
game/client/hl2/c_energy_wave.cpp
game/client/hl2/c_env_alyxtemp.cpp
game/client/hl2/c_env_headcrabcanister.cpp
game/client/hl2/c_env_starfield.cpp
game/client/hl2/c_extinguisher.cpp
game/client/hl2/C_Func_Monitor.cpp
game/client/hl2/c_func_tankmortar.cpp
game/client/hl2/c_hl2_playerlocaldata.cpp
game/client/hl2/c_info_teleporter_countdown.cpp
game/client/hl2/clientmode_hlnormal.cpp
game/client/hl2/c_npc_antlionguard.cpp
game/client/hl2/c_npc_combinegunship.cpp
game/client/hl2/c_npc_hydra.cpp
game/client/hl2/c_npc_manhack.cpp
game/client/hl2/c_npc_rollermine.cpp
game/client/hl2/c_plasma_beam_node.cpp
game/client/hl2/c_prop_combine_ball.cpp
game/client/hl2/c_rotorwash.cpp
game/client/hl2/c_script_intro.cpp
game/client/hl2/c_strider.cpp
game/client/hl2/c_te_concussiveexplosion.cpp
game/client/hl2/c_te_flare.cpp
game/client/hl2/c_thumper_dust.cpp
game/client/hl2/c_vehicle_airboat.cpp
game/client/hl2/c_vehicle_cannon.cpp
game/client/hl2/c_vehicle_crane.cpp
game/client/hl2/c_vehicle_prisoner_pod.cpp
game/client/hl2/c_waterbullet.cpp
game/client/hl2/c_weapon_crossbow.cpp
game/client/hl2/c_weapon_gravitygun.cpp
game/client/hl2/c_weapon_physcannon.cpp
game/client/hl2/c_weapon__stubs_hl2.cpp
game/client/hl2/c_weapon_stunstick.cpp
game/client/hl2/fx_antlion.cpp
game/client/hl2/fx_bugbait.cpp
game/client/hl2/fx_hl2_impacts.cpp
game/client/hl2/fx_hl2_tracers.cpp
game/client/hl2/hl2_clientmode.cpp
game/client/hl2/hl_in_main.cpp
game/client/hl2/hl_prediction.cpp
game/client/hl2/hud_ammo.cpp
game/client/hl2/hud_autoaim.cpp
game/client/hl2/hud_battery.cpp
game/client/hl2/hud_blood.cpp
game/client/hl2/hud_bonusprogress.cpp
game/client/hl2/hud_credits.cpp
game/client/hl2/hud_damageindicator.cpp
game/client/hl2/hud_filmdemo.cpp
game/client/hl2/hud_flashlight.cpp
game/client/hl2/hud_hdrdemo.cpp
game/client/hl2/hud_health.cpp
game/client/hl2/hud_locator.cpp
game/client/hl2/hud_poisondamageindicator.cpp
game/client/hl2/hud_quickinfo.cpp
game/client/hl2/hud_radar.cpp
game/client/hl2/hud_suitpower.cpp
game/client/hl2/hud_weaponselection.cpp
game/client/hl2/hud_zoom.cpp
game/client/hl2mp/c_hl2mp_player.cpp
game/client/hl2mp/clientmode_hl2mpnormal.cpp
game/client/hl2mp/c_te_hl2mp_shotgun_shot.cpp
game/client/hl2mp/hl2mp_hud_chat.cpp
game/client/hl2mp/hl2mp_hud_target_id.cpp
game/client/hl2mp/hl2mp_hud_team.cpp
game/client/hl2mp/hud_deathnotice.cpp
game/client/hl2mp/ui/backgroundpanel.cpp
game/client/hl2mp/ui/hl2mpclientscoreboard.cpp
game/client/hl2mp/ui/hl2mptextwindow.cpp
game/client/hl2/shieldproxy.cpp
game/client/hl2/vgui_rootpanel_hl2.cpp
game/client/hltvcamera.cpp
game/client/hud_animationinfo.cpp
game/client/hud_base_account.cpp
game/client/hud_basechat.cpp
game/client/hud_basedeathnotice.cpp
game/client/hud_basetimer.cpp
game/client/hud_bitmapnumericdisplay.cpp
game/client/hud_chat.cpp
game/client/hud_closecaption.cpp
game/client/hud_controlpointicons.cpp
game/client/hud_controlpointpanel.cpp
game/client/hud.cpp
game/client/hud_crosshair.cpp
game/client/hud_element_helper.cpp
game/client/hud_hintdisplay.cpp
game/client/hud_lcd.cpp
game/client/hud_msg.cpp
game/client/hud_numericdisplay.cpp
game/client/hud_pdump.cpp
game/client/hud_posture.cpp
game/client/hud_redraw.cpp
game/client/hud_squadstatus.cpp
game/client/hud_vehicle.cpp
game/client/hud_vguiscreencursor.cpp
game/client/hud_voicestatus.cpp
game/client/hud_vote.cpp
game/client/hud_weapon.cpp
game/client/in_camera.cpp
game/client/in_forcefeedback.cpp
game/client/initializer.cpp
game/client/in_joystick.cpp
game/client/in_main.cpp
game/client/in_mouse.cpp
game/client/interpolatedvar.cpp
game/client/IsNPCProxy.cpp
game/client/lampbeamproxy.cpp
game/client/lamphaloproxy.cpp
game/client/mathproxy.cpp
game/client/matrixproxy.cpp
game/client/menu.cpp
game/client/message.cpp
game/client/MonitorMaterialProxy.cpp
game/client/movehelper_client.cpp
game/client/mp3player.cpp
game/client/mumble.cpp
game/client/panelmetaclassmgr.cpp
game/client/particle_collision.cpp
game/client/particle_litsmokeemitter.cpp
game/client/particlemgr.cpp
game/client/particle_prototype.cpp
game/client/particle_proxies.cpp
game/client/particles_attractor.cpp
game/client/particles_ez.cpp
game/client/particle_simple3d.cpp
game/client/particles_localspace.cpp
game/client/particles_new.cpp
game/client/particlesphererenderer.cpp
game/client/particles_simple.cpp
game/client/perfvisualbenchmark.cpp
game/client/physics.cpp
game/client/physics_main_client.cpp
game/client/physpropclientside.cpp
game/client/playerandobjectenumerator.cpp
game/client/playerspawncache.cpp
game/client/prediction.cpp
game/client/proxyentity.cpp
game/client/ProxyHealth.cpp
game/client/proxyplayer.cpp
game/client/proxypupil.cpp
game/client/ragdoll.cpp
game/client/recvproxy.cpp
game/client/rendertexture.cpp
game/client/replay/cdll_replay.cpp
game/client/replay/gamedefs.cpp
game/client/replay/genericclassbased_replay.cpp
game/client/replay/replaycamera.cpp
game/client/replay/replayperformanceplaybackhandler.cpp
game/client/replay/replay_ragdoll.cpp
game/client/replay/replayrenderer.cpp
game/client/replay/replay_screenshot.cpp
game/client/replay/replayvideo.cpp
game/client/replay/replayyoutubeapi.cpp
game/client/replay/replayyoutubeapi_key_sdk.cpp
game/client/replay/vgui/replaybrowserbasepage.cpp
game/client/replay/vgui/replaybrowserbasepanel.cpp
game/client/replay/vgui/replaybrowserdetailspanel.cpp
game/client/replay/vgui/replaybrowseritemmanager.cpp
game/client/replay/vgui/replaybrowserlistitempanel.cpp
game/client/replay/vgui/replaybrowserlistpanel.cpp
game/client/replay/vgui/replaybrowsermainpanel.cpp
game/client/replay/vgui/replaybrowsermovieplayerpanel.cpp
game/client/replay/vgui/replaybrowserpreviewpanel.cpp
game/client/replay/vgui/replaybrowserrenderdialog.cpp
game/client/replay/vgui/replayconfirmquitdlg.cpp
game/client/replay/vgui/replayinputpanel.cpp
game/client/replay/vgui/replaymessagepanel.cpp
game/client/replay/vgui/replayperformanceeditor.cpp
game/client/replay/vgui/replayperformancesavedlg.cpp
game/client/replay/vgui/replayreminderpanel.cpp
game/client/replay/vgui/replayrenderoverlay.cpp
game/client/ScreenSpaceEffects.cpp
game/client/sdk/clientmode_sdk.cpp
game/client/sdk/c_sdk_env_sparkler.cpp
game/client/sdk/c_sdk_player.cpp
game/client/sdk/c_sdk_team.cpp
game/client/sdk/c_te_firebullets.cpp
game/client/sdk/sdk_fx_impacts.cpp
game/client/sdk/sdk_fx_weaponfx.cpp
game/client/sdk/sdk_hud_ammo.cpp
game/client/sdk/sdk_hud_chat.cpp
game/client/sdk/sdk_hud_health.cpp
game/client/sdk/sdk_hud_message.cpp
game/client/sdk/sdk_hud_weaponselection.cpp
game/client/sdk/sdk_in_main.cpp
game/client/sdk/sdk_prediction.cpp
game/client/sdk/vgui/sdkviewport.cpp
game/client/sdk/vgui/vgui_rootpanel_sdk.cpp
game/client/simple_keys.cpp
game/client/sixense/in_sixense.cpp
game/client/sixense/in_sixense_gesture_bindings.cpp
game/client/smoke_fog_overlay.cpp
game/client/splinepatch.cpp
game/client/spritemodel.cpp
game/client/stdafx.cpp
game/client/studio_stats.cpp
game/client/TeamBitmapImage.cpp
game/client/text_message.cpp
game/client/texturescrollmaterialproxy.cpp
game/client/thermalmaterialproxy.cpp
game/client/timematerialproxy.cpp
game/client/toggletextureproxy.cpp
game/client/toolframework_client.cpp
game/client/train.cpp
game/client/vgui_avatarimage.cpp
game/client/vgui_basepanel.cpp
game/client/vgui_bitmapbutton.cpp
game/client/vgui_bitmapimage.cpp
game/client/vgui_bitmappanel.cpp
game/client/vgui_centerstringpanel.cpp
game/client/vgui_consolepanel.cpp
game/client/vgui_debugoverlaypanel.cpp
game/client/vgui_entityimagepanel.cpp
game/client/vgui_entitypanel.cpp
game/client/vgui_fpspanel.cpp
game/client/vgui_game_viewport.cpp
game/client/vgui_grid.cpp
game/client/vgui_imagehealthpanel.cpp
game/client/vgui_int.cpp
game/client/vgui_loadingdiscpanel.cpp
game/client/vgui_messagechars.cpp
game/client/vgui_netgraphpanel.cpp
game/client/vgui_schemevisualizer.cpp
game/client/vgui_slideshow_display_screen.cpp
game/client/vgui_textmessagepanel.cpp
game/client/vgui_video.cpp
game/client/vgui_video_player.cpp
game/client/viewangleanim.cpp
game/client/view_beams.cpp
game/client/ViewConeImage.cpp
game/client/view.cpp
game/client/viewdebug.cpp
game/client/view_effects.cpp
game/client/viewpostprocess.cpp
game/client/viewrender.cpp
game/client/view_scene.cpp
game/client/voice_menu.cpp
game/client/warp_overlay.cpp
game/client/WaterLODMaterialProxy.cpp
game/client/weapon_selection.cpp
game/client/weapons_resource.cpp
game/client/WorldDimsProxy.cpp
)

set(HEADERS_GAME_CLIENT
game/client/achievement_notification_panel.h
game/client/animationlayer.h
game/client/baseanimatedtextureproxy.h
game/client/baseclientrendertargets.h
game/client/basepresence.h
game/client/beamdraw.h
game/client/bone_merge_cache.h
game/client/bonetoworldarray.h
game/client/c_ai_basenpc.h
game/client/c_baseanimating.h
game/client/c_baseanimatingoverlay.h
game/client/c_basecombatcharacter.h
game/client/c_basecombatweapon.h
game/client/c_basedoor.h
game/client/c_baseentity.h
game/client/c_baseflex.h
game/client/cbase.h
game/client/c_baseplayer.h
game/client/c_basetempentity.h
game/client/c_baseviewmodel.h
game/client/c_breakableprop.h
game/client/cdll_bounded_cvars.h
game/client/cdll_client_int.h
game/client/cdll_util.h
game/client/c_effects.h
game/client/c_entitydissolve.h
game/client/c_env_fog_controller.h
game/client/C_Env_Projected_Texture.h
game/client/c_fire_smoke.h
game/client/c_func_dust.h
game/client/c_func_reflective_glass.h
game/client/c_gib.h
game/client/c_impact_effects.h
game/client/cl_animevent.h
game/client/clienteffectprecachesystem.h
game/client/cliententitylist.h
game/client/client_factorylist.h
game/client/clientleafsystem.h
game/client/clientmode.h
game/client/clientmode_normal.h
game/client/clientmode_shared.h
game/client/clientsideeffects.h
game/client/clientsteamcontext.h
game/client/client_thinklist.h
game/client/client_virtualreality.h
game/client/cl_mat_stub.h
game/client/colorcorrectionmgr.h
game/client/commentary_modelviewer.h
game/client/c_physbox.h
game/client/c_physicsprop.h
game/client/c_pixel_visibility.h
game/client/c_playerlocaldata.h
game/client/c_playerresource.h
game/client/c_point_camera.h
game/client/c_props.h
game/client/c_prop_vehicle.h
game/client/c_recipientfilter.h
game/client/c_rope.h
game/client/c_rumble.h
game/client/c_sceneentity.h
game/client/c_slideshow_display.h
game/client/c_smoke_trail.h
game/client/c_soundscape.h
game/client/c_sprite.h
game/client/c_sun.h
game/client/c_team.h
game/client/c_team_objectiveresource.h
game/client/c_team_train_watcher.h
game/client/c_te_basebeam.h
game/client/c_te_effect_dispatch.h
game/client/c_te_legacytempents.h
game/client/c_te_particlesystem.h
game/client/c_tesla.h
game/client/c_tracer.h
game/client/c_user_message_register.h
game/client/c_vehicle_jeep.h
game/client/c_vguiscreen.h
game/client/c_vote_controller.h
game/client/c_weapon__stubs.h
game/client/c_world.h
game/client/detailobjectsystem.h
game/client/enginesprite.h
game/client/episodic/episodic_screenspaceeffects.h
game/client/flashlighteffect.h
game/client/fontabc.h
game/client/functionproxy.h
game/client/fx_blood.h
game/client/fx_discreetline.h
game/client/fx_envelope.h
game/client/fx_explosion.h
game/client/fx_fleck.h
game/client/fx.h
game/client/fx_impact.h
game/client/fx_interpvalue.h
game/client/fx_line.h
game/client/fx_quad.h
game/client/fx_sparks.h
game/client/fx_staticline.h
game/client/fx_trail.h
game/client/fx_water.h
game/client/game_controls/basemodel_panel.h
game/client/game_controls/basemodelpanel.h
game/client/game_controls/baseviewport.h
game/client/game_controls/buymenu.h
game/client/game_controls/buysubmenu.h
game/client/game_controls/classmenu.h
game/client/game_controls/clientscoreboarddialog.h
game/client/game_controls/commandmenu.h
game/client/game_controls/IconPanel.h
game/client/game_controls/imagemouseoverbutton.h
game/client/game_controls/intromenu.h
game/client/game_controls/mapoverview.h
game/client/game_controls/mouseoverhtmlbutton.h
game/client/game_controls/mouseoverpanelbutton.h
game/client/game_controls/NavProgress.h
game/client/game_controls/spectatorgui.h
game/client/game_controls/teammenu.h
game/client/game_controls/vguitextwindow.h
game/client/glow_outline_effect.h
game/client/glow_overlay.h
game/client/history_resource.h
game/client/hl2/c_basehelicopter.h
game/client/hl2/c_basehlcombatweapon.h
game/client/hl2/c_basehlplayer.h
game/client/hl2/c_corpse.h
game/client/hl2/c_hl2_playerlocaldata.h
game/client/hl2/clientmode_hlnormal.h
game/client/hl2/c_prop_combine_ball.h
game/client/hl2/c_vehicle_crane.h
game/client/hl2/hud_radar.h
game/client/hl2/hud_suitpower.h
game/client/hl2mp/c_hl2mp_player.h
game/client/hl2mp/clientmode_hl2mpnormal.h
game/client/hl2mp/hl2mp_hud_chat.h
game/client/hl2mp/ui/backgroundpanel.h
game/client/hl2mp/ui/hl2mpclientscoreboard.h
game/client/hl2mp/ui/hl2mptextwindow.h
game/client/hltvcamera.h
game/client/hud_base_account.h
game/client/hud_basechat.h
game/client/hud_basedeathnotice.h
game/client/hud_basetimer.h
game/client/hud_bitmapnumericdisplay.h
game/client/hud_chat.h
game/client/hud_closecaption.h
game/client/hud_controlpointicons.h
game/client/hud_crosshair.h
game/client/hudelement.h
game/client/hud_element_helper.h
game/client/hud.h
game/client/hud_lcd.h
game/client/hud_macros.h
game/client/hud_numericdisplay.h
game/client/hud_pdump.h
game/client/hudtexturehandle.h
game/client/hud_vehicle.h
game/client/hud_vote.h
game/client/iclassmap.h
game/client/icliententityinternal.h
game/client/iclientmode.h
game/client/iclientshadowmgr.h
game/client/iclientvehicle.h
game/client/iconsole.h
game/client/idebugoverlaypanel.h
game/client/ifpspanel.h
game/client/ihudlcd.h
game/client/iinput.h
game/client/iloadingdisc.h
game/client/imessagechars.h
game/client/inetgraphpanel.h
game/client/initializer.h
game/client/in_main.h
game/client/input.h
game/client/interpolatedvar.h
game/client/ipresence.h
game/client/iprofiling.h
game/client/itextmessage.h
game/client/ivieweffects.h
game/client/iviewrender_beams.h
game/client/iviewrender.h
game/client/ivmodemanager.h
game/client/kbutton.h
game/client/lerp_functions.h
game/client/menu.h
game/client/movehelper_client.h
game/client/mp3player.h
game/client/mumble.h
game/client/networkstringtable_clientdll.h
game/client/panelmetaclassmgr.h
game/client/particle_collision.h
game/client/particledraw.h
game/client/particle_iterators.h
game/client/particle_litsmokeemitter.h
game/client/particlemgr.h
game/client/particle_prototype.h
game/client/particles_attractor.h
game/client/particles_ez.h
game/client/particle_simple3d.h
game/client/particles_localspace.h
game/client/particles_new.h
game/client/particlesphererenderer.h
game/client/particles_simple.h
game/client/particle_util.h
game/client/perfvisualbenchmark.h
game/client/physics.h
game/client/physpropclientside.h
game/client/playerandobjectenumerator.h
game/client/playerenumerator.h
game/client/playerspawncache.h
game/client/prediction.h
game/client/prediction_private.h
game/client/proxyentity.h
game/client/ragdollexplosionenumerator.h
game/client/ragdoll.h
game/client/recvproxy.h
game/client/rendertexture.h
game/client/replay/cdll_replay.h
game/client/replay/gamedefs.h
game/client/replay/genericclassbased_replay.h
game/client/replay/replaycamera.h
game/client/replay/replayperformanceplaybackhandler.h
game/client/replay/replay_ragdoll.h
game/client/replay/replayrenderer.h
game/client/replay/replay_screenshot.h
game/client/replay/replayvideo.h
game/client/replay/replayyoutubeapi.h
game/client/replay/vgui/replaybrowserbasepage.h
game/client/replay/vgui/replaybrowserbasepanel.h
game/client/replay/vgui/replaybrowserdetailspanel.h
game/client/replay/vgui/replaybrowseritemmanager.h
game/client/replay/vgui/replaybrowserlistitempanel.h
game/client/replay/vgui/replaybrowserlistpanel.h
game/client/replay/vgui/replaybrowsermainpanel.h
game/client/replay/vgui/replaybrowsermovieplayerpanel.h
game/client/replay/vgui/replaybrowserpreviewpanel.h
game/client/replay/vgui/replaybrowserrenderdialog.h
game/client/replay/vgui/replayconfirmquitdlg.h
game/client/replay/vgui/replayinputpanel.h
game/client/replay/vgui/replaymessagepanel.h
game/client/replay/vgui/replayperformanceeditor.h
game/client/replay/vgui/replayperformancesavedlg.h
game/client/replay/vgui/replayreminderpanel.h
game/client/replay/vgui/replayrenderoverlay.h
game/client/ScreenSpaceEffects.h
game/client/sdk/clientmode_sdk.h
game/client/sdk/c_sdk_player.h
game/client/sdk/c_sdk_team.h
game/client/sdk/sdk_hud_chat.h
game/client/sdk/vgui/sdkviewport.h
game/client/sdk/vgui/vgui_rootpanel_sdk.h
game/client/simple_keys.h
game/client/sixense/in_sixense_gesture_bindings.h
game/client/sixense/in_sixense.h
game/client/smoke_fog_overlay.h
game/client/splinepatch.h
game/client/studio_stats.h
game/client/TeamBitmapImage.h
game/client/tempent.h
game/client/text_message.h
game/client/timedevent.h
game/client/toggletextureproxy.h
game/client/toolframework_client.h
game/client/vgui_avatarimage.h
game/client/vgui_basepanel.h
game/client/vgui_bitmapbutton.h
game/client/vgui_bitmapimage.h
game/client/vgui_bitmappanel.h
game/client/vguicenterprint.h
game/client/vgui_entityimagepanel.h
game/client/vgui_entitypanel.h
game/client/vgui_game_viewport.h
game/client/vgui_grid.h
game/client/vgui_helpers.h
game/client/vgui_imagehealthpanel.h
game/client/vgui_int.h
game/client/vgui_schemevisualizer.h
game/client/vgui_video.h
game/client/vgui_video_player.h
game/client/viewangleanim.h
game/client/ViewConeImage.h
game/client/viewdebug.h
game/client/view.h
game/client/viewpostprocess.h
game/client/viewrender.h
game/client/view_scene.h
game/client/weapon_selection.h
game/client/weapons_resource.h
)
